# Generated by Django 5.1.3 on 2024-11-22 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_note_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='conent',
            new_name='content',
        ),
    ]
